name: estimulo2020
description: Aplicativo Estimulo 2020.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.coSm/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  youtube_player_flutter: ^7.0.0+7
  carousel_slider: ^2.3.1
  http: ^0.12.2
  fluttertoast: ^7.1.1
  adobe_xd: ^1.0.0+1
  

  flutter:
    sdk: flutter
   
  flutter_launcher_icons: "^0.7.3"


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages

  assets:
    - assets/logo.png
    - assets/profile-picture.gif
    - assets/userregister.png
    - assets/senha.png
    - assets/mentoria.png
    - assets/capacitacao.png
    - assets/acompanhamento.png
    - assets/avatar.png
    - assets/estimulo_logo.png
    - assets/relatorio.png
    - assets/teacher-avatar.png
    - assets/mentoria2.png
    - assets/mentoria3.png
    - assets/profile-picture.png
    - assets/business-man-avatar.png
    - assets/reset-password-icon.png
    - assets/report.png
    - assets/financeiro.png
    - assets/marketing.png
    - assets/recursos_humanos.png
    - assets/tecnologia_e_inovacao.png
    
  fonts:
     - family: Raleway
       fonts:
        - asset: assets/fonts/JosefinSans-Bold.ttf
        - asset: assets/fonts/Raleway-Regular.ttf
        - asset: assets/fonts/Raleway-Bold.ttf
           